DIBTP-E2E/KFE3-dibtp

packages/ui/src/design-system/tailwindcss-styles/design-tokens/color-tokens/primitive-colors.css, packages/ui/src/design-system/tailwindcss-styles/design-tokens/color-tokens/scale-colors.css, packages/ui/src/design-system/tailwindcss-styles/design-tokens/color-tokens/semantic-colors.css, packages/ui/src/design-system/tailwindcss-styles/design-tokens/index.css, packages/ui/src/design-system/tailwindcss-styles/design-tokens/spacing-tokens.css, packages/ui/src/design-system/tailwindcss-styles/design-tokens/typography-tokens.css, packages/ui/src/design-system/tailwindcss-styles/semantic-styles/colors-styles.css, packages/ui/src/design-system/tailwindcss-styles/semantic-styles/typography-styles.css, packages/ui/src/global.css, packages/ui/src/globals.css
#13 
- [피그마의 디자인시스템](https://www.figma.com/design/Ot6ISy4LNWvSYooB7gHYo0/-KFE3-%E1%84%92%E1%85%A1%E1%86%BA%E1%84%83%E1%85%B5%E1%86%AF-%E1%84%8C%E1%85%AE%E1%86%BC%E1%84%80%E1%85%A9-%E1%84%80%E1%85%A5%E1%84%85%E1%85%A2-E2E-5%EC%A1%B0?node-id=2-4&t=wMIRo2BkEuAqjkld-1) 기준 색상, 타이포 전역 토큰 생성
- taliwindcss 의 기능을 이용하여 시맨틱 색상의 유틸 클래스와 시맨틱 타이포의 커스텀 클래스 생성
- 피그마의 스타일 가이드와 색상이 매칭되어 적용되어 있는지 확인이 필요합니다.
- 생성한 유틸클래스가 자동완성이 잘 되는지 확인이 필요합니다.
- 기존 디자인 시스템은 기존 컴포넌트에서 사용되고 있으므로 삭제 하지 않았습니다.
- 컴포넌트가 새로운 디자인시스템으로 대체될 경우 기존 디자인시스템은 제거할 예정입니다.
=> [feat] 디자인 시스템과 tailwindcss 유틸클래스 설정 #13

packages/ui/src/design-system/base-components/Input/index.ts, packages/ui/src/design-system/base-components/Textarea/LabeledTextarea.tsx, packages/ui/src/design-system/base-components/Textarea/Textarea.tsx, packages/ui/src/design-system/base-components/Textarea/index.ts, packages/ui/src/design-system/base-components/Textarea/stories/LabeledTextarea.stories.tsx, packages/ui/src/design-system/base-components/Textarea/stories/Textarea.stories.tsx
Textarea와 LabelTextarea 컴포넌트와 스토리를 추가하였습니다.
=> [feat] 디자인 시스템 Textarea 컴포넌트 추가

apps/web/app/(pages)/layout.tsx, apps/web/app/(pages)/products/page.tsx, apps/web/styles/globals.css, packages/ui/package.json
=> [bug] Web app에서 UI 패키지의 컴포넌트를 import 할 때 스타일이 적용되지 않는 이슈 해결 #50

packages/ui/src/design-system/base-components/Icons/Icons.stories.tsx
=> [refactor] 아이콘 컴포넌트 스토리북 경로 수정 #59

packages/ui/src/design-system/base-components/Thumbnail/Thumbnail.stories.tsx, packages/ui/src/design-system/base-components/Thumbnail/Thumbnail.tsx, packages/ui/src/design-system/base-components/Thumbnail/index.ts, packages/ui/src/design-system/base-components/index.ts
- Thumbnail 컴포넌트 생성
- Thumbnail 컴포넌트 스토리 추가
=> [feat] UI 패키지에 Thumbnail 컴포넌트 생성 #70

apps/web/app/(pages)/products/[productId]/data.ts, apps/web/app/(pages)/products/[productId]/page.tsx, apps/web/components/product-detail/AuctionInfoLayout.tsx, apps/web/components/product-detail/AuctionSummary.tsx, apps/web/components/product-detail/BackButton.tsx, apps/web/components/product-detail/BidButton.tsx, apps/web/components/product-detail/ChatButton.tsx, apps/web/components/product-detail/CurrentPrice.tsx, apps/web/components/product-detail/ImageCounter.tsx, apps/web/components/product-detail/LikeButton.tsx, apps/web/components/product-detail/NextButton.tsx, apps/web/components/product-detail/NextPrice.tsx, apps/web/components/product-detail/PrevButton.tsx, apps/web/components/product-detail/ProductDescription.tsx, apps/web/components/product-detail/ProductDetailHeader.tsx, apps/web/components/product-detail/ProductFooter.tsx, apps/web/components/product-detail/ProductImageCarousel.tsx, apps/web/components/product-detail/ProductTitle.tsx, apps/web/components/product-detail/SellerAvatar.tsx, apps/web/components/product-detail/SellerNickname.tsx, apps/web/components/product-detail/UserInfoLayout.tsx, apps/web/components/product-detail/index.ts, apps/web/components/shared/Timer.tsx, apps/web/components/shared/index.ts
상품 상세 페이지 UI를 구현했습니다.
<image src="https://github.com/user-attachments/assets/1716610d-766c-463b-98a0-f676798e6b52" width="50%"/>
=> [feat] 상품 상세 조회 페이지 구현 #22

apps/web/constants/storage-bucket.ts
supabase storage 버킷 public으로 새로 생성해서 버킷명 수정
=> fix: 이미지 bucket 변경으로 인해 수정 (#81)

apps/web/components/product-detail/BackButton.tsx, apps/web/hooks/products/useProductForm.ts, apps/web/next.config.ts
- #89 이슈에서 발생되는 에러 제거하기 위해 더이상 지원하지 않는 next의 폰트 최적화 옵션 optimizeFonts 제거
- 더이상 사용하지 않는 /products 페이지로 라우팅 되는 부분을 메인 페이지로 이동하도록 수정
=> [hotfix] 지원하지 않는 next font 최적화 옵션 제거 #89

README.md
README.md 파일을 전면적으로 개선하여 프로젝트에 대한 이해도를 높이고 개발자 경험을 향상시켰습니다.
- **기술 스택 상세화**: Frontend, Backend, Development Tools, External APIs로 카테고리 분류
- **기능 설명 체계화**: 6개 주요 기능 섹션으로 구조화하여 상세 설명
- **프로젝트 개요 보강**: 목적, 특징, 개발 진행 단계 추가
- **로드맵 제시**: 3단계 개발 계획을 체계적으로 제시
- **문서 구조 개선**: 독자 친화적인 순서로 재구성
🔧 변경 사항
[x] 📃 README.md
[ ] 📦 package.json
[ ] 🔥 파일 삭제
[ ] 🧹 그 외 ex) .gitignore 등
📸 스크린샷 (선택 사항)
📄 기타
=> docs: README.md E2E버전으로 수정

apps/web/components/products/ProductCard.tsx
=> [feat] 상품 상세 페이지 라우팅 추가 #97

apps/web/package.json
=> [fix] 빌드 에러 수정 #101

apps/web/app/(auth-pages)/location/page.tsx, apps/web/app/(home)/page.tsx, apps/web/components/products/ProductList.tsx, apps/web/components/products/index.ts
suspense와 skeleton이 적용된 상품리스트 컴포넌트가 만들어져있지만 사용되지 않아서
홈페이지에서 사용하는 ProductList 컴포넌트를 ProductListWithSuspense 컴포넌트로 변경
=> [fix] 홈페이지의 상품리스트 suspense 적용

apps/web/app/(pages)/products/[productId]/page.tsx, apps/web/app/layout.tsx, apps/web/components/layout/BottomNavigation.tsx, apps/web/components/layout/TopNavigation.tsx, apps/web/components/product-detail/ProductDetailHeader.tsx, apps/web/components/product-detail/ProductFooter.tsx, packages/tailwind-config/design-tokens/index.css
현재 레이아웃이 너비 375px 고정값으로 그 이상의 크기의 모바일 화면에서 좌우 여백이 발생하여 모바일 한정 반응형으로 수정
- breakpoint md 사이즈에서 부터 max-width 값 적용되도록 수정
- max-width 값 토큰으로 관리하도록 수정
- md 사이즈를 768px 에서 sm의 2배 값인 752px 로 수정
=> [feat] 모바일 레이아웃 고정값에서 모바일 한정 반응형으로 수정 #88

apps/web/app/(home)/page.tsx, apps/web/package.json, pnpm-lock.yaml
- 메인 페이지 ```export const dynamic = 'force-dynamic';``` 추가
=> [fix] 버셀 빌드 오류 관련 재수정 #113

.github/workflows/chromatic.yml
#134 
#135 이어서 수정
- chromatic.yml 파일에서 누락된 build 단계 추가
=> [chore] chromatic.yml 파일에서 누락된 build 단계 추가

apps/web/app/api/images/route.ts, apps/web/middleware.ts, apps/web/utils/auth/auth-utils.ts
closes #153
인증 관련 코드와 미들웨어의 일관성 개선 및 최적화 작업을 수행했습니다.
- **인증 유틸리티 import 경로 표준화**: barrel export 패턴 적용
- **auth-utils.ts 코드 정리**: 불필요한 지시문 제거 및 인터페이스 확장
- **미들웨어 최적화**: PWA 관련 요청 처리 개선
1. **Import 경로 일관성 개선**
- `@/utils/auth/auth-utils` → `@/utils/auth` 로 변경
- 이미 존재하는 barrel export 패턴 활용
2. **auth-utils.ts 개선**
- 불필요한 `'use server'` 지시문 제거
- AuthResult 인터페이스에 email 필드 추가
- 서버 환경 사용 명시 주석 추가
3. **미들웨어 최적화**
- manifest.json 파일을 미들웨어 검증 예외 경로에 추가
- import 구문 포맷팅 개선
- **수정된 파일**: `apps/web/app/api/images/route.ts`, `apps/web/middleware.ts`, `apps/web/utils/auth/auth-utils.ts`
- **기능 개선**: 코드 일관성 향상, PWA 지원 개선, 타입 안전성 강화
이 리팩토링은 기능 변경 없이 코드 품질과 일관성을 개선하는 작업입니다. 
- 모든 기존 기능은 정상 동작
- PWA manifest.json 요청 최적화로 성능 개선
=> refactor: 인증 유틸리티 모듈 개선 및 미들웨어 정리 (#153)

apps/web/components/screen/SearchScreen/SearchScreen.tsx, apps/web/components/search/index.ts
- SearchScreen 에서 import 경로 수정한 사항을 반영하지 않아서 컴파일 에러가 나고 있어서 수정했습니다
=> fix: 누락된 import 수정사항 반영 (#182)

apps/web/app/(pages)/chat/layout.tsx
빌드 에러의 원인인지 모르겠지만 컴파일 에러 수정 후 로컬에서 빌드했을 때 통과했습니다
=> [fix] 채팅 페이지 레이아웃 컴파일 에러 해결 #185

.github/workflows/git-push.yml, build.sh
=> remove: 사용하지 않는 build.sh 파일 제거

apps/web/app/(pages)/mypage/(mypage)/page.tsx, apps/web/app/(pages)/mypage/bids/page.tsx, apps/web/app/(pages)/mypage/sales/page.tsx, apps/web/app/(pages)/products/register/page.tsx, apps/web/app/(pages)/search/page.tsx
=> [fix] 빌드 에러 해결 : supabase auth 관련 페이지 SSG 를 dynamic으로 수정 #227

apps/web/app/api/chat/messages/read/route.ts, apps/web/components/chat/ChatRoom/ChatRoom.tsx
=> fix: 여러 메시지 읽을 때만 생기는 무한 루프 현상 제거 (#229)

apps/web/app/api/users/[userId]/route.ts
빌드 에러 중 api route의 users/[userId]/route.ts 파일의 params의 타입을 promise 타입으로 수정
=> fix: 빌드 에러 수정, params 타입 수정 (#234)

apps/web/middleware.ts
- 미들웨어 설정을 성능 최적화 관점에서 개선하기 위해 기존의 정적 파일 제외 방식에서 인증이 필요한 경로만 명시적으로 포함하는 방식으로 변경
- 미들웨어 config 최적화: 정적 리소스 제외 패턴 제거하고 필요한 경로만 명시
- 성능 개선: 불필요한 미들웨어 실행 최소화
- 유지보수성 향상: 복잡한 정규식 패턴 대신 명확한 경로 리스트 사용
**Before**
```ts
export const config = {
matcher: [
/*
* Match all request paths except for the ones starting with:
* - _next/static (static files)
* - _next/image (image optimization files)
* - favicon.ico (favicon file)
* - sw.js (service worker)
* - manifest files
* - static assets
*/
'/((?!_next/static|_next/image|favicon.ico|sw.js|manifest|.*\\.(?:svg|png|jpg|jpeg|gif|webp|ico|json|js|css|woff|woff2)$).*)',
],
};
// 정적 파일이 생길 때 마다 정규식 패턴에 추가 (robots.txt, sitemap.xml 등..)
'/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml|sw.j …
```
=> [pref] auth 확인이 필요한 네트워크 요청에서만 미들웨어가 동작하도록 성능 개선 (#250)

apps/web/components/bid-history/BidHistoryCard.tsx, apps/web/components/products/ProductCard.tsx, apps/web/components/products/ProductList.tsx, apps/web/components/sales/SalesProductCard.tsx, apps/web/components/sales/SalesProductList.tsx, apps/web/types/bid/domain.ts, apps/web/utils/bids/mapBidHistoryResponse.ts, pnpm-lock.yaml
상품 노출 지역 단위 수정에 따라 상세 주소도 상품 카드에 나타나도록 수정함
=> refactor : ProductCard에 detail_address prop 추가 및 관련 컴포넌트 수정 #252

apps/web/utils/auth/server/index.ts
빌드 에러 확인하여 수정 
- 제거된 auth-utils 모듈 barrel export 제거
- 📃 apps/web/utils/index.ts
=> fix: auth-utils 모듈 제거하여 barrel export 제거 (#269)

.github/workflows/release.yml, CHANGELOG.md, scripts/generate-release-notes.js
=> fix: 릴리즈 버전 중복 생성 문제 해결 

apps/web/app/(pages)/mypage/(mypage)/page.tsx, apps/web/components/layout/header-icon/AlarmButton.tsx, apps/web/components/mypage/MypageMenuItem.tsx, apps/web/components/mypage/SettingsMenu.tsx, apps/web/components/mypage/TradingMenu.tsx
아직 구현되지 않은 기능(알림 버튼, 관심목록, 계정설정, 알림설정)의 UI 요소에 준비중 토스트 처리
활동 통계 숨김 처리
=> refactor: 아직 구현되지 않은 기능의 UI 요소에 준비중 토스트 처리

apps/web/app/(pages)/products/[productId]/(detail)/page.tsx, apps/web/components/product-detail/AuctionInfoLayout.tsx, apps/web/components/product-detail/BidButton.tsx, apps/web/components/product-detail/CurrentPrice.tsx, apps/web/components/product-detail/LikeButton.tsx, apps/web/components/product-detail/ProductDetailHeader.tsx, apps/web/components/product-detail/ProductFooter.tsx, apps/web/components/product-detail/StatusActionButton.tsx, apps/web/components/product-detail/UserInfoLayout.tsx, apps/web/components/products/ProductList.tsx, apps/web/components/products/ProductThumb.tsx, apps/web/components/shared/SkeletonBox.tsx, apps/web/components/shared/index.ts, apps/web/hooks/favorites/useFavoriteStatus.ts, apps/web/hooks/my-info/useMyInfo.ts, apps/web/hooks/products/useCurrentPrice.ts, apps/web/hooks/users/useUserInfo.ts, apps/web/services/favorites/client/fetchFavoriteStatus.ts, apps/web/services/favorites/client/index.ts, apps/web/services/my-info/server/getMyInfo.ts, apps/web/services/products/server/getMyProducts.ts, apps/web/services/products/server/getProducts.ts, apps/web/types/my-info/api.ts, apps/web/types/product/api.ts, apps/web/utils/products/product-mappers.ts
- 상품 상세 페이지 `page.tsx` 서버 컴포넌트에서 처리하던 비동기 로직을 일부 클라이언트단으로 분리함으로써 `page.tsx`에서 생기던 병목 현상 해결
- 클라이언트 컴포넌트 측에 비동기 로직 추가되면서 로딩시 스켈레톤 UI 추가
- 상품 리스트 카드에 현재가격 `created_at` 기준으로 가격 표시하던 것 `auction_started_at` 기준으로 표시하도록 수정
=> [refactor] 상품 상세 페이지 및 상품 리스트 리팩토링 #276

apps/web/public/sw.js
가끔씩 오류를 발생시키는 서비스워커 동작하지 않도록 주석 처리
=> fix: 안정성을 위해 서비스워커 주석 처리 
