DIBTP-E2E/KFE3-dibtp

apps/web/app/layout.tsx
apps/web/next.config.ts
apps/web/providers/QueryProvider.tsx
apps/web/styles/globals.css
packages/tailwind-config/shared-styles.css
packages/ui/src/global.css

#5 
노토산스 폰트가 web 렌더링 화면에서 적용되지 않는 이유 파악 및 적용
- app router 용도의 디렉토리와 구분하기 위해 router와 의존성이 없는 디렉토리는 app 바깥으로 이동
- `apps/web/app/globals.css` -> `apps/web/styles/globals.css` 로 파일 위치 이동
- `apps/web/app/providers/*` -> `apps/web/providers/*`로 파일 위치 이동
- globals.css 내부 수정 
- globals.css가 참조하고 있지만 존재 하지 않은 `@repo/ui/styles.css` import 문구 제거
- globals.css가 참조하고 있지만 존재 하지 않은 `@repo/tailwind-config` 내 `packgages.json`에서 정의하고 있는 `shared-styles.css` 파일 생성
```json
{
"name": "@repo/tailwind-config",
"version": "0.0.0",
"type": "module",
"private": true,
"exports": {
".": "./shared-styles.css", // 여기서 정의된 파일이 실존하지 않음.
"./postcss": "./postcss.config.js"
},
"devDependencies": {
"postcss": "^8.5.3",
"tailwindcss": "^4.1.5"
}
}
```
- `shared-styles.css` 파일에서 기존 tailwindcss에서 사용하는 유틸클래스 `font-sans` 를 @theme …

[fix] Noto Sans KR 폰트가 웹에서 반영되지 않는 이슈 수정 #5

---

lefthook.yml

#6 
- web 디렉토리 내 next js 의 app router 역할을 하는 app 디렉토리와 다른 파일들의 역할을 구분하기 위에 app 디렉토리 내부에 있는 globals.css 파일과 providers 디렉토리의 위치를 이동하는 과정에서 eslint 이슈 확인
- 이슈의 원인은 lefthook.yml 파일에서 web 디렉토리로 위치를 이동한 상태에서 다시 'apps/web/**/*.{js,ts,jsx,tsx}' 파일을 찾도록 설정이 되어있기 때문이며 apps/web/apps/web 경로는 존재하지 않기 때문에 lefthook.yml 내용 수정
```yml
eslint-web:
glob: 'apps/web/**/*.{js,ts,jsx,tsx}'
// 수정 전 
run: pnpm --filter=web exec eslint {staged_files} --fix && echo "ESLint ran on {staged_files}"
// 수정 후
run: cd apps/web && pnpm exec eslint $(echo "{staged_files}" | sed 's|apps/web/||g') --fix && echo "ESLint ran on web files"
stage_fixed: true
```

[fix] eslint 가 수정된 파일 위치를 찾지 못하는 이슈를 해결하기 위한 lefthook.yml 파일 수정 #6

---

apps/docs/.storybook/main.ts
apps/docs/.storybook/preview.ts
apps/docs/tsconfig.json
apps/web/.storybook/main.ts
apps/web/.storybook/preview.ts
apps/web/components/login/LoginButton.stories.tsx
apps/web/package.json
package.json
packages/ui/package.json
pnpm-lock.yaml
turbo.json

- turbo run storybook 실행 시 수행되는 task가 없으므로 docs app의 스토리북이 실행되도록 설정 추가
- web app 내 스토리북 설치
- web app의 스토리북과 ui 패키지의 스토리북을 통합하도록 docs app 스토리북에 연결
- 렌더링 화면 이슈 해결
- turbo run storybook 실행 시 docs app의 스토리북이 실행된 화면
**루트에서 스토리북 실행 명령어**
- `turbo run storybook` 또는 `pnpm storybook` : docs app의 스토리북 실행 (web app, ui 패키지의 통합 문서)
- `pnpm storybook:web` : web app의 스토리북 실행
- `pnpm storybook:ui` : ui package의 스토리북 실행

[chore] turbo run storybook 실행 시 docs app의 스토리북이 실행되도록 설정 #29

---

apps/web/app/(pages)/products/page.tsx
packages/ui/package.json
packages/ui/src/design-system/base-components/Avatar/Avatar.tsx
packages/ui/src/design-system/base-components/Badge/Badge.tsx
packages/ui/src/design-system/base-components/Icons/Icon.tsx
packages/ui/src/design-system/base-components/Input/Input.tsx
packages/ui/src/design-system/base-components/Input/PasswordInput.tsx
packages/ui/src/design-system/base-components/Input/components/PasswordToggle.tsx
packages/ui/src/design-system/base-components/Label/Label.tsx
packages/ui/src/design-system/base-components/index.ts
packages/ui/src/design-system/design-token-stories/colors/PrimitiveColors.stories.tsx
packages/ui/src/design-system/design-token-stories/colors/SemanticColors.stories.tsx
packages/ui/src/design-system/design-token-stories/colors/UtilityColors.stories.tsx
packages/ui/src/storybook-components/Section.tsx
packages/ui/src/storybook-components/StoryPage.tsx
packages/ui/src/utils/storybook/color-token-utils.ts
packages/ui/tsconfig.json

- UI 패키지 내 상대경로를 절대경로로 사용하도록 설정 추가
- web app에서 ui 패키지의 컴포넌트를 `@import { Input, Icon } from '@repo/ui/components'` 형태로 사용가능하도록 설정

[chore] ui 패키지 내 절대경로 설정 #54

---

packages/ui/src/design-system/base-components/Button/Button.stories.tsx
packages/ui/src/design-system/base-components/Button/Button.tsx
packages/ui/src/design-system/base-components/Button/index.ts
packages/ui/src/design-system/base-components/index.ts

- UI 버튼 컴포넌트 와 스토리 생성
**주요 기능**
- 6가지 미리 정의된 variant (Primary/Secondary/Danger의 Filled/Outlined 조합)
- 3가지 크기 지원 (sm, md, lg)
- 다양한 HTML 요소로 렌더링 가능 (button, a, div, span)
- 전체 너비 및 비활성화 상태 지원
**as prop 사용 가이드**
- button: 기본값, 일반적인 버튼 용도
- a: 링크 기능이 필요한 경우
- div/span: react-router-dom의 `<Link>` 와 함께 사용할 때 태그 중복 방지를 위해 사용합니다. Next.js의 `<Link>`는 자식이 태그일 경우 a 요소 중복이 자동 제거되므로 태그 사용 권장합니다. 불필요한 div, span 사용은 지양
- Next에서 사용할 경우
```
<Link>
<Button as="a">버튼</Button>
</Link>
// 렌더링 결과: a 요소 중복 제거
<a>버튼</a>
```
- react-router-dom에서 사용할 경우
```
<Link>
<Button as="a">버튼</Button>
</Link>
// 렌더링 결과 : a 요소 중복
<a><a class="tailwind-style">버튼</a></a>
// 사용시 
<Link>
<Button as="div">버튼</Button>
</Link>
// 렌더링 결과
<a><div class="tailwind-style">버튼</div></a>
```
추가적으로 전달하고 싶은 내용이나 특별한 요구 사항이 …

[feat] 버튼 컴포넌트 생성

---

apps/web/app/api/images/route.ts
apps/web/components/ui/ImageUpload.tsx
apps/web/constants/index.ts
apps/web/constants/product-images.ts
apps/web/constants/storage-bucket.ts
apps/web/lib/storage/index.ts
apps/web/lib/storage/storage.ts
apps/web/lib/validations/image.ts
apps/web/lib/validations/index.ts
apps/web/services/images/client/deleteImages.ts
apps/web/services/images/client/index.ts
apps/web/services/images/client/uploadImages.ts
apps/web/services/images/index.ts
apps/web/services/images/server/deleteFromStorage.ts
apps/web/services/images/server/index.ts
apps/web/services/images/server/uploadToStorage.ts
apps/web/services/index.ts
apps/web/types/image.ts
apps/web/types/index.ts
apps/web/utils/image/image-utils.ts
apps/web/utils/image/index.ts
apps/web/utils/index.ts
packages/ui/src/design-system/base-components/Icons/assets/Icons.ts

상품 등록 시 이미지 업로드, 미리보기, 관리 기능을 구현했습니다.
- 이미지 업로드 컴포넌트
- 스토리지 관리
- 유틸리티 및 타입
- 컴포넌트: ImageUpload.tsx - 메인 이미지 업로드 UI
- API: app/api/images/route.ts - 이미지 CRUD API
- 서비스: services/images/ - 클라이언트/서버 이미지 처리
- 스토리지: lib/storage/ - 스토리지 연동 라이브러리
- 타입: types/image.ts - 이미지 관련 타입 정의
- 유틸: utils/image/ - 이미지 처리 유틸리티
- 상수: constants/ - 이미지 관련 설정값

[feat] 이미지 업로드 및 스토리지 관리 기능 구현

---

apps/web/app/(pages)/products/[productId]/page.tsx
apps/web/components/products/ProductCard.tsx
apps/web/components/products/ProductList.tsx
apps/web/components/products/ProductThumb.tsx
apps/web/components/shared/ProductBadge.tsx
apps/web/services/products/fetchProductDetail.ts
apps/web/services/products/fetchProducts.ts
apps/web/types/product/api.ts

- 상품 상세페이지 fetch 서비스 함수 생성 및 상세 정보 조회 기능 구현
- 상품 상세페이지의 목데이터를 supabase fetch 데이터 적용하도록 수정
- 상품 리스트 클릭 시 상품 id 조회하도록 페이지 라우팅 적용
- product 타입 리팩토링 및 업데이트

[feat] 상품 상세 페이지 서비스 함수 생성 및 데이터 fetch #91

---

.github/workflows/release.yml

closes #137
GitHub Actions의 release 워크플로우에서 기존 태그 중복으로 인한 오류를 수정했습니다.
1. **Release 액션 태그 중복 오류 수정**
- 기존 태그 존재 여부를 확인하는 로직 추가
- 태그가 이미 존재하는 경우 생성을 건너뛰도록 수정
- `allowUpdates: true` 옵션으로 릴리즈 업데이트 허용
2. **토큰 설정 개선**
- `GITHUB_TOKEN` 대신 `RELEASE_TOKEN` 사용으로 권한 문제 해결
- `.github/workflows/release.yml`
**release.yml:**
- 태그 생성 전 기존 태그 존재 여부 확인 로직 추가
- `allowUpdates: true` 옵션 추가
- `RELEASE_TOKEN` 사용으로 변경

fix: release 액션에서 기존 태그 중복 오류 수정

---

.github/workflows/chromatic.yml

ISSUE #141 
#140 PR에서 turbo 명령어 실행시 ui 패키지 호출 명 오탈자를 확인 
**⏺ Turborepo --filter 규칙**
- 기본 원칙: package.json의 name 필드와 정확히 일치해야 함
- apps/web 의 경우 : `"name": "web"`
- apps/docs 의 경우 : "name": "@repo/ui"
**⏺ Scoped Package vs Regular Package 필터링 규칙 상세 설명:**
NPM Scoped Package 정의
Scoped Package는 @scope/name 형태의 패키지입니다:
- @ 기호로 시작하는 조직/사용자 네임스페이스
- 예: @repo/ui, @typescript-eslint/parser, @tanstack/react-query
Regular Package는 일반적인 패키지 이름:
- 단순한 이름 형태
- 예: web, react, lodash
공식 문서 출처:
- https://turbo.build/repo/docs/reference/run
- https://docs.npmjs.com/cli/v10/using-npm/scope
**⏺ Monorepo 패키지 네이밍 컨벤션 분석:**
- 현재 프로젝트의 네이밍 패턴
packages/ui/         → @repo/ui      (scoped)
apps/docs/          → @apps/docs     (scoped)
apps/web/           → web …

fix: chromatic.yml 파일에서 turbo 명령어의 ui 호출 오탈자 수정 #141

---

apps/web/app/(pages)/mypage/layout.tsx
apps/web/app/(pages)/mypage/page.tsx
apps/web/components/mypage/ActivityCard.tsx
apps/web/components/mypage/ActivityStats.tsx
apps/web/components/mypage/LogoutButton.tsx
apps/web/components/mypage/MypageHeader.tsx
apps/web/components/mypage/MypageMenuItem.tsx
apps/web/components/mypage/MypageSectionCard.tsx
apps/web/components/mypage/SettingsMenu.tsx
apps/web/components/mypage/TradingMenu.tsx
apps/web/components/mypage/index.ts
apps/web/constants/navigation.ts
apps/web/lib/supabase/middleware.ts
packages/ui/src/design-system/base-components/Icons/assets/Icons.ts
packages/ui/src/design-system/base-components/Icons/index.ts

closes #151
마이페이지 UI 구성요소와 로그아웃 기능을 구현했습니다.
- 마이페이지 레이아웃 및 페이지 구조 설계
- 사용자 프로필 헤더 컴포넌트 (닉네임, 프로필 이미지 표시)
- 활동 통계 컴포넌트 (판매/구매 현황)
- 거래 관리 메뉴 (판매내역, 구매내역, 관심목록)
- 설정 메뉴 (위치설정, 알림설정, 계정설정)
- Supabase 연동 로그아웃 기능
- 마이페이지 관련 아이콘 추가
- 네비게이션에 마이페이지 링크 추가
- 미들웨어 보호 경로 설정
- **새로 추가된 파일**: 마이페이지 레이아웃, 페이지, 컴포넌트 11개
- **수정된 파일**: 네비게이션, 미들웨어, 아이콘 리소스
- **기능 구현**: 사용자 인증 기반 페이지 접근 제어
- 모든 링크는 향후 구현 예정 페이지로 연결

feat: 마이페이지 UI 및 로그아웃 기능 구현 (#151)

---

apps/docs/.storybook/main.ts
apps/web/components/layout/header-icon/CloseTextButton.tsx
apps/web/components/layout/header-icon/HeaderIconButton.tsx
packages/ui/src/design-system/base-components/Avatar/Avatar.tsx
packages/ui/src/design-system/base-components/Badge/Badge.tsx
packages/ui/src/design-system/base-components/Button/Button.stories.tsx
packages/ui/src/design-system/base-components/Button/Button.tsx
packages/ui/src/design-system/base-components/Button/index.ts
packages/ui/src/design-system/base-components/IconButton/IconButton.stories.tsx
packages/ui/src/design-system/base-components/IconButton/IconButton.tsx
packages/ui/src/design-system/base-components/IconButton/index.ts
packages/ui/src/design-system/base-components/Icons/Icon.tsx
packages/ui/src/design-system/base-components/Icons/index.ts
packages/ui/src/design-system/base-components/Input/Input.tsx
packages/ui/src/design-system/base-components/Input/PasswordInput.tsx
packages/ui/src/design-system/base-components/Input/components/PasswordToggle.tsx
packages/ui/src/design-system/base-components/Label/Label.stories.tsx
packages/ui/src/design-system/base-components/Label/Label.tsx
packages/ui/src/design-system/base-components/Label/index.ts
packages/ui/src/design-system/base-components/Thumbnail/Thumbnail.tsx
packages/ui/src/design-system/base-components/Thumbnail/index.ts
packages/ui/tsconfig.json

**💥 이슈 관련 수정 작업**
- 이슈에서 확인되는 버그가 ui 컴포넌트내 에서 외부 경로 @repo/ui 를 사용하는 것을 확인하여 import 문 수정
- ui 내 패키지 import 문 수정과 함께 dods 에서 스토리북 별칭 해석 문제로 임시방편 처리한  경로별 1:1 매칭 제거하여 @ui 별칭 사용하여 리팩토링
- 관련 자세한 이슈 확인  -> #161 
**👀 기타 콘솔 에러 발견**
- 제거했던 button 컴포넌트의 `isTransparent` 속성을 사용하는 CloseTextButton 컴포넌트를 확인하여 `isTransparent` 속성을 다시 추가 
- button 컴포넌트 에서 `isTransparent` 속성을 사용할 경우에 대한 스토리북 문서에 예시 추가
`CloseTextButton` 컴포넌트가 헤더에서 기대하는 `isTransparent` 속성의 효과
- 헤더에서 사용하는 다른 컴포넌트와 같은 사이즈 및 부피감으로 사용자 터치의 사용감을 높여줌
- 실제 인터랙셕이 가능한 면적
- 스토리북에 `isTransparent` 사용 가이드 추가

[fix] IconButton import 문 경로 수정 이슈 해결 및 UI 패키지 내 절대경로 별칭을 @ 에서 @ui로 수정 #161

---

packages/ui/src/design-system/base-components/Textarea/LabeledTextarea.tsx
packages/ui/src/design-system/design-token-stories/colors/PrimitiveColors.stories.tsx
packages/ui/src/design-system/design-token-stories/colors/SemanticColors.stories.tsx
packages/ui/src/design-system/design-token-stories/colors/UtilityColors.stories.tsx
packages/ui/src/storybook-components/Section.tsx
packages/ui/src/storybook-components/StoryPage.tsx
packages/ui/src/utils/storybook/color-token-utils.ts

closes #167
UI 패키지의 import 경로 오류를 수정하여 TypeScript 빌드 실패 문제를 해결했습니다.
- `/products/register` 페이지 접근 시 발생하던 `LabeledTextarea` 컴포넌트 오류
- UI 패키지 빌드 시 발생하던 "Module has no exported member" 오류
- 스토리북 파일들의 정의되지 않은 경로 별칭 사용 문제
1. **LabeledTextarea 컴포넌트 import 경로 수정**
- `import { Label } from '../Label/Label'` → `import { Label } from '../Label'`
- `import { FormMessage } from '../FormMessage/FormMessage'` → `import { FormMessage } from '../FormMessage'`
2. **스토리북 컴포넌트 경로 별칭 수정**
- `import { cn } from '@/utils/cn'` → `import { cn } from '@ui/utils/cn'`
3. **스토리북 스토리 파일 import 경로 수정**
- `import { ... } from '@/storybook-components'` → `import { ... } from '@ui/storybook-components'`
4. **색상 토큰 유틸리티 경로 수정**
- `import { ... } from '@/design-system/...'` → `import { ... } from '@ui/design-system/...'`
총 …

fix: ui 패키지 import 경로 오류 수정 (#167)

---

apps/docs/.storybook/main.ts
apps/web/components/product-register/ImageUpload.tsx
apps/web/components/product-register/ProductRegisterForm.tsx
apps/web/components/product-register/index.ts
apps/web/tsconfig.json

설명참고 : #164 
- web app 내 @web 별칭도 사용가능하도록 추가
- docs app의 스토리북 경로 설정 시 @web, @ 2가지 별칭 모두 web app의 경로를 바라보도록 설정 추가

[refactor] web app 내 @web 별칭을 점진적으로 사용 가능하도록 절대경로 별칭 추가 설정 #164

---

apps/web/app/layout.tsx
packages/ui/src/design-system/base-components/ActionSheet/ActionSheet.stories.tsx
packages/ui/src/design-system/base-components/ActionSheet/ActionSheet.tsx
packages/ui/src/design-system/base-components/ActionSheet/index.ts
packages/ui/src/design-system/base-components/BottomSheet/BottomSheet.stories.tsx
packages/ui/src/design-system/base-components/BottomSheet/BottomSheet.tsx
packages/ui/src/design-system/base-components/BottomSheet/hooks/index.ts
packages/ui/src/design-system/base-components/BottomSheet/hooks/useBottomSheetGestures.ts
packages/ui/src/design-system/base-components/BottomSheet/hooks/useBottomSheetState.ts
packages/ui/src/design-system/base-components/BottomSheet/index.ts
packages/ui/src/design-system/base-components/index.ts

closes #180
UI 디자인 시스템에 BottomSheet와 ActionSheet 컴포넌트를 추가했습니다.
- 터치 제스처 지원으로 스와이프하여 닫기 기능 구현
- 백드롭 클릭으로 닫기 기능 (옵션으로 비활성화 가능)
- 접근성 지원 (포커스 트랩, ESC 키 지원)
- 반응형 높이 조절 및 스크롤 처리
- 애니메이션과 상태 관리를 위한 커스텀 훅 분리
- BottomSheet를 기반으로 한 액션 리스트 컴포넌트
- danger 상태의 배경색과 텍스트 색상 일관성 확보
- 비활성화 상태 및 취소 버튼 옵션 지원
- **BottomSheet**:새로운 컴포넌트 추가
- **ActionSheet**: 새로운 컴포넌트 추가
- ActionSheet 
- BottomSheet
- backdrop filter 제거 버전
backdrop filter가 없는 버전이 덜 답답해보여서 빼는걸로 수정하겠습니다!

feat: bottomsheet 및 actionsheet 컴포넌트 추가 (#180)

---

.github/workflows/chromatic.yml

아래 이미지와 같이 story를 수정하거나 생성했을 때에도 storybook deploy 단계가 스킵되는 현상 해결
- `detech-changes` 단계에서 발생하는 output의 디렉토리 명과 `chromatic-storybook` 단계의 if 문의 디렉토리 명이 일치하지 않아서 생기는 문제이므로 if 문 수정
- `detect-changes` 에서 생기는 outputs의 디렉토리들은 ui-changed, web-changed, docs-changed
```yml
jobs:
detect-changes:
runs-on: ubuntu-latest
outputs:
ui-changed: ${{ steps.changes.outputs.ui }}
web-changed: ${{ steps.changes.outputs.web }}
docs-changed: ${{ steps.changes.outputs.docs }}
```
- `chromatic-storybook` if 문 수정 전
```yml
chromatic-storybook:
runs-on: ubuntu-latest
name: Deploy Storybook to Chromatic
needs: detect-changes
if: needs.detect-changes.outputs.ui== 'true' || needs.detect-changes.outputs.web== 'true' || needs.detect-changes.outputs.docs== 'true' || github.ref == 'refs/heads/main'
``` 
- …

fix: chromatic.yml 파일에서 chromatic-storybook 단계가 skip 되는 이슈 해결 (#198)

---

apps/web/components/search/RecentKeywords.tsx
packages/ui/src/design-system/base-components/FormMessage/FormMessage.tsx
packages/ui/src/design-system/base-components/IconButton/IconButton.stories.tsx
packages/ui/src/design-system/base-components/Icons/assets/Icons.ts
packages/ui/src/design-system/base-components/Input/components/PasswordToggle.tsx

-  의존하고 있는 리액트 아이콘 패밀리 종류가 다양할수록 리액트 아이콘 번들 사이즈가 커지는 문제가 있어서 최대한 유사한 아이콘을 선택하면서도 의존하는 아이콘 패밀리를 최소화 할 수 있는 방향으로 코드 리팩토링

[refactor] 리액트 아이콘 번들 최소화 #257

---

.github/workflows/release.yml
CHANGELOG.md

closes #267
GitHub Actions의 릴리즈 노트 자동화 시스템에서 발생하던 두 가지 주요 문제를 해결했습니다:
1. **CHANGELOG.md 자동 업데이트 미작동 문제**: `## [Unreleased]` 섹션이 없어서 스크립트가 CHANGELOG.md를 업데이트하지 못하던 문제를 해결했습니다.
2. **버전 중복 오류 문제**: package.json의 현재 버전과 새 버전이 동일할 때 `pnpm version` 명령어가 실패하던 문제를 해결했습니다.
주요 변경 사항:
- Keep a Changelog 형식에 맞는 `## [Unreleased]` 섹션 추가
- 표준 섹션들 (Added, Changed, Fixed, Removed) 추가
- 현재 package.json 버전과 새 버전 비교 로직 추가
- 버전이 동일한 경우 graceful handling
- CHANGELOG.md 파일도 git에 추가하여 자동 커밋되도록 수정
- 버전 업데이트 실패 시에도 CHANGELOG.md는 업데이트되도록 개선
- `npm error Version not changed` 오류 해결
- CHANGELOG.md가 업데이트되지 않던 문제 해결
이제 다음 릴리즈부터는 CHANGELOG.md가 자동으로 업데이트되고, 버전 중복으로 인한 GitHub Actions 실패가 발생하지 않습니다.

fix: 릴리즈 노트 자동화 시스템 개선 및 CHANGELOG.md 업데이트 기능 수정 #267

---

.github/workflows/release.yml
CHANGELOG.md

changelog.md를 업데이트 하는 깃허브 액션이 실행되서 changelog.md 파일이 업데이트 될 때마다
계속해서 깃허브 액션이 새로 실행되는 무한루프를 수정했습니다.

fix: 릴리즈 노트 작성 자동화 오류 수정 (#267)

---

apps/web/components/shared/PWAManager.tsx

PWA 앱 설치 안내를 하는 UI 의 텍스트 문구가 잘 보이지 않고 버튼이 제대로 동작하지 않는 이슈 해결

[fix] PWA Manager UI 가독성 개선 (#277)

---

apps/web/middleware.ts

- 로그인 직후 배포 환경 에러 비상사태
- middleware matcher list 정리 후 로그인 후 쿠키 셋팅하지 않아서 생긴 이슈이므로 일단 기존대로 복구

[hotfix] 로그인 후 인증 로직 누락되어 다시 middleware의 matcher 복구 (#282)
